#!/bin/zsh
#
# Write/remove a task to do later.
#
# Select an existing entry to remove it from the file, or type a new entry to
# add it.
#

file="$HOME/.config/calcurse/todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="Add/delete a task: "

cmd=$(sort -r "$file" | dmenu -l "$height" -p "$prompt" -i )
while [ -n "$cmd" ]; do
  if grep -qF "$cmd" "$file"; then
		grep -vF "$cmd" "$file" > "$file.new"
		mv "$file.new" "$file"
    (( height = height - 1 ))
 	else
    if [[ "$(echo $cmd | tr -d \\n)" =~ "^\[[[:digit:]]\]" ]]; then
      echo "$cmd" >> "$file"
    else
      echo "[0] $cmd" >> "$file"
    fi
    cmd=""
    (( height = height + 1 ))
 	fi

  cmd=$(sort -r "$file" | dmenu -l "$height" -p "$prompt" -it "$cmd" "$@" )
done

exit 0
